services:
  devops:
    build:
      context: ./
    environment:
      # Move the history file to be in the volume
      - HISTFILE=/root/bash_history/.bash_history
    volumes:
      # Store the history
      - devops_history:/root/bash_history
      # Volume in the repo rather than copying it (saves time on start)
      - ./:/root/repo
      # Just in case we have any ssh to deal with
      - $HOME/.ssh:/root/.ssh
      # enable aws access
      - ~/.aws:/root/.aws
volumes:
  devops_history: